apiVersion: v1
kind: Pod
metadata:
  name: worblehat-adam
  namespace: worblehat
  labels:
    owner: adam
spec:
  containers:
  - name: worblehat
    image: docker.io/lsstsqre/worblehat:ajt-dev
    imagePullPolicy: Always
    env:
    - name: WORBLEHAT_BASE_HREF
      value: "/files/adam"
    - name: WORBLEHAT_TIMEOUT
      value: "3600"
    - name: WORBLEHAT_DIR
      value: "/mnt"
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP      
    volumeMounts:
    - mountPath: /mnt
      name: share
  restartPolicy: Never
  securityContext:
    fsGroup: 3000001
    runAsNonRoot: true
    supplementalGroups:
    - 3000001
    - 2000004
    - 2000003
  volumes:
  - name: share
    nfs:
      path: /share1
      server: 10.87.86.26
      # 10.87.86.26 is dev
      # 10.22.240.130 is int
      # 10.13.105.122 is prod
  

    
    
