apiVersion: v1
kind: Pod
metadata:
  name: worblehat-{{username}}
  namespace: worblehat
  labels:
    owner: {{username}}
spec:
  containers:
  - name: worblehat
    image: docker.io/lsstsqre/worblehat:ajt-dev
    imagePullPolicy: Always
    env:
    - name: WORBLEHAT_BASE_HREF
      value: "/files/{{username}}"
    - name: WORBLEHAT_DIR
      value: "/mnt"
    - name: WORBLEHAT_TIMEOUT
      value: "3600"
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: /mnt
      name: share
  restartPolicy: Never
  securityContext:
    runAsUser: {{uid}}
    runAsGroup: {{gid}}
    fsGroup: {{gid}}
    runAsNonRoot: true
    supplementalGroups: {{gids}}
  volumes:
  - name: share
    nfs:
      path: {{serverPath}}
      server: {{serverIP}}
  

    
    
