apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: fileservers
    lsst.io/category: fileserver
    lsst.io/user: {{username}}
  name: {{username}}-fs
  namespace: fileservers
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    lsst.io/category: fileserver
    lsst.io/user: {{username}}
  type: ClusterIP
