apiVersion: v1
kind: Service
metadata:
  name: worblehat-{{username}}
  namespace: worblehat
  labels:
    owner: {{username}}
spec:
  type: "ClusterIP"
  ports:
    - port: 8000
      targetPort: 8000
      protocol: "TCP"
  selector:
    owner: {{username}}
