name: CI

"on":
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "renovate/**"
      - "tickets/**"
      - "t/**"
      - "u/**"
    tags:
      - "*"
  pull_request: {}

jobs:

  build:
    uses: lsst-sqre/multiplatform-build-and-push/.github/workflows/build.yaml@v1
    with:
      images: ghcr.io/${{ github.repository }}
    secrets: inherit
    if: >
      startsWith(github.ref, 'refs/tags/')
      || startsWith(github.head_ref, 'tickets/')
      || startsWith(github.head_ref, 't/')
